# The outbox: an event, written in the same transaction as the thing it
# describes.
#
# Generated by `rails generate cafaye:outbox` from `Cafaye::Outbox::DDL`, which
# is core's column list plus the CHECK constraints from core's event-envelope
# schema. The column list is core's, not a local invention —
# cafaye/core: docs/event-outbox.md — and `test/contract/core_specs_test.rb`
# in the cafaye-rb repository checks this file's ancestor against core's own.
#
# The event goes in from `after_create`/`after_update`, never from `after_commit`
# and never from a background job. `after_commit` is a window in which the
# database says the row exists and the event does not; a background job is the
# same window with a queue in it. A rollback of the record takes the event with
# it, and a commit makes both durable together.
#
# `Cafaye.outbox.publish!` refuses to write outside a transaction, so the pairing
# cannot be broken by forgetting this comment.
#
# `event_type` rather than `type` is not cosmetic: on any Active Record model a
# column named `type` is single-table inheritance, and a row whose value is
# `billing.customer.created` would send Rails looking for a class with that name.
class CreateOutboxEvents < ActiveRecord::Migration[<%= ActiveRecord::Migration.current_version %>]
  def change
    create_table :outbox_events, id: :uuid do |t|
      # The envelope's `id`, generated before the insert and reused on every
      # retry, so a republish is the same id and a consumer's dedupe key dedupes.
      t.string :event_type, null: false
      t.string :source, null: false
      # Required, and `platform` for an event with no single entity: a required
      # field with a reserved value is a value a consumer can always read.
      t.string :subject, null: false
      # When the state change happened — not when the row was inserted and not
      # when it is published. A row that sat unpublished for an hour still
      # reports the original time, and an event stamped on arrival makes
      # out-of-order delivery undetectable.
      t.column :time, :timestamptz, null: false
      # `jsonb` rather than `json`: it is parsed, so a contract test or a query
      # can reach inside the payload, and it normalises key order so two
      # identical payloads are byte-identical.
      t.jsonb :data, null: false
      # Null until the transport acknowledges. This is the only definition of
      # "published" — not "attempted", not "handed to a client".
      t.column :published_at, :timestamptz
      # Publish attempts so far: the input to backoff and the signal alerts on.
      t.integer :attempts, null: false, default: 0
      t.column :created_at, :timestamptz, null: false
    end

    # core's eventType pattern, verbatim. The first segment is a cafaye service
    # name and is kebab-case, so it may contain a dash and never an underscore.
    # A malformed type is refused here rather than at every consumer on the
    # platform, which is where a format error is most expensive to find.
    add_check_constraint :outbox_events,
                         "event_type ~ '^[a-z][a-z0-9]*(-[a-z0-9]+)*\.[a-z][a-z0-9]*(_[a-z0-9]+)*\.[a-z][a-z0-9]*(_[a-z0-9]+)*$'",
                         name: "outbox_events_event_type_format"

    # core's serviceName pattern. A service name never contains a dot, so this
    # also catches a `source` that is actually a full event type.
    add_check_constraint :outbox_events,
                         "source ~ '^[a-z][a-z0-9]*(-[a-z0-9]+)*$'",
                         name: "outbox_events_source_format"

    # core's subject pattern and its 1..200 length bound, in one constraint. The
    # subject is interpolated into consumer logs and routing keys, so the
    # character set is deliberately narrow.
    add_check_constraint :outbox_events,
                         "subject ~ '^[A-Za-z0-9][A-Za-z0-9._:@/-]*$' and length(subject) between 1 and 200",
                         name: "outbox_events_subject_format"

    # The three-segment type names its own publisher. A row whose `source` is not
    # the first segment of its `type` is a row two consumers would route
    # differently, and nothing downstream would notice until one of them was
    # wrong.
    add_check_constraint :outbox_events,
                         "split_part(event_type, '.', 1) = source",
                         name: "outbox_events_source_matches_type"

    # A `jsonb` column holding a scalar is a payload no contract test can reach
    # inside and no query can select from.
    add_check_constraint :outbox_events,
                         "jsonb_typeof(data) = 'object'",
                         name: "outbox_events_data_is_an_object"

    # A negative attempt count would make the backoff schedule undefined.
    add_check_constraint :outbox_events,
                         "attempts >= 0",
                         name: "outbox_events_attempts_not_negative"

    # The publisher's only query. Without this it is a sequential scan of every
    # event the service has ever published, forever. Partial, because published
    # rows are spent.
    add_index :outbox_events, %i[created_at id],
              where: "published_at IS NULL", name: "outbox_events_unpublished_idx"

    # Per-entity ordering is the one ordering core guarantees, so this is the one
    # index the guarantee needs behind it.
    add_index :outbox_events, %i[subject created_at], name: "outbox_events_subject_created_at_idx"
  end
end
